#!/bin/bash
# Script para gerar senhas seguras
# Slackjeff <lrcjefferson@gmail.com>
# Opção Byns 14 é para 14 digitos
# Aumentando a senha obviamente irá aumentar tbm.

clear
senha=`pwgen -Byns 14 1 | tee /home/$USER/senha.txt`
echo
echo "================================================"
echo "Gerador de senhas"
echo "================================================"
echo "Sua senha é: $senha"
echo "Senha gravada em: /home/$USER/senha.txt"
echo "================================================"
